Fault and Twist controller from new repo
Kinovarobotics/ros2_kortex pull request #143
Opened 2023-07-04 13:38 UTC by moriarty

- We aim to have these two controllers merged into ros2_control
- For now get them from picknik_controllers repo

2023-07-04 13:41 UTC, moriarty commented
Heads up @eholum Breaking this out into it's own thing might affect MoveIt Studio because of how it pulls in dependencies, it will need to have a dependency on picknik_controllers

2023-07-05 14:22 UTC, abake48 requested changes
one small change and then I'll approve

2023-07-05 14:22 UTC, abake48 commented on README.md
>  This metapackage contains the auto-generated MoveIt! files to use the Kinova Gen3 and Gen3 lite arms with the MoveIt! motion planning framework. For more details, please consult the [README](kortex_m
```suggestion
This metapackage contains the auto-generated MoveIt! files to use the Kinova Gen3 and Gen3 lite arms with the MoveIt! motion planning framework. For more details, please consult the [README](kortex_moveit_config/readme.md) from the package subdirectory.
```

2023-07-05 14:32 UTC, abake48 approved these changes

2023-07-05 14:32 UTC, merged

2023-07-05 14:33 UTC, abake48 commented
Studio should be safe until we migrate over to the latest main. 

That will be a part of my todos for moving the Kinova robot configs out of the core Studio repo and into their own workspace repo