clean up default controller names
Kinovarobotics/ros2_kortex pull request #145
Opened 2023-07-06 14:23 UTC by abake48

Updated fault controller name in yaml files and cleaned up gen3.launch.py and kortex_control.launch.py

2023-07-09 14:48 UTC, moriarty approved these changes

2023-07-09 14:49 UTC, moriarty submitted a review, later dismissed

2023-07-09 15:02 UTC, moriarty commented
@abake48 I think you found a naming an error on my part and opened PR https://github.com/PickNikRobotics/picknik_controllers/pull/9

2023-07-11 15:57 UTC, moriarty requested changes
It should be PicknikResetFaultController
https://github.com/PickNikRobotics/picknik_controllers/pull/9

2023-07-11 15:57 UTC, moriarty commented on kortex_description/arms/gen3/7dof/config/ros2_controllers.yaml
> -      type: picknik_reset_fault_controller/PicknikResetFaultController
Are you sure your workspace is up to date and has been cleaned if needed?
It looks like you're changing this back from what it should be to what it was.

2023-07-14 20:14 UTC, abake48 commented
@moriarty This PR is ready for re-review

2023-07-14 21:05 UTC, moriarty commented on kortex_description/arms/gen3/6dof/config/ros2_controllers.yaml
> +      type: picknik_reset_fault_controller/FaultController
@abake48 is this PicknikResetFaultController or just FaultController?

2023-07-14 21:46 UTC, abake48 commented on kortex_description/arms/gen3/6dof/config/ros2_controllers.yaml
> +      type: picknik_reset_fault_controller/FaultController
Whoops, forgot the 6dof. It should be `PicknikResetFaultController`

2023-07-17 16:29 UTC, moriarty approved these changes

2023-07-17 22:51 UTC, merged