Repo update
Kinovarobotics/ros2_kortex pull request #220
Opened 2024-05-23 18:14 UTC by smoya23

- Creating a specific launch file for Gen3 Lite robots
- Fixing and updating the MoveIt configs for Gen3 robots
- Restructuring documentation for clarity

2024-05-23 18:33 UTC, martinleroux requested changes
Good stuff, some fixes still required. See pending comments.

2024-05-23 18:33 UTC, martinleroux commented on README.md
> +* `dof` : Degrees of freedom of the arm. Possible values for the Gen3 are either `6` or `7`. For the Gen3 Lite, the only option is `6`. Default value is `7`.
Can we have the logic so the argument is ignored for Gen3 lite? To avoid problems with the default value.

2024-05-23 18:33 UTC, martinleroux commented on README.md
> +* `robot_controller` : Robot controller to start. Default value is `joint_trajectory_controller`.
Are there other options?

2024-05-23 18:33 UTC, martinleroux commented on kortex_description/grippers/gen3_lite_2f/urdf/gen3_lite_2f.ros2_control.xacro
> +        robot_ip:=192.168.1.10
Add a comment: 192.168.2.10 when using USB to Ethernet interface instead of USB via RNDIS

2024-05-23 19:57 UTC, smoya23 commented on kortex_description/grippers/gen3_lite_2f/urdf/gen3_lite_2f.ros2_control.xacro
> +        robot_ip:=192.168.1.10
Added comment in the README arguments explanation

2024-05-23 19:58 UTC, smoya23 commented on README.md
> +* `dof` : Degrees of freedom of the arm. Possible values for the Gen3 are either `6` or `7`. For the Gen3 Lite, the only option is `6`. Default value is `7`.
Good point, I removed the argument completely from the launch file and set the value to 6

2024-05-24 13:45 UTC, martinleroux approved these changes

2024-05-24 13:45 UTC, merged