Added Gen3 + Husky
Kinovarobotics/ros2_kortex pull request #240
Opened 2024-09-26 20:49 UTC by aalmrad

Added Gen3 7DoF integration with Husky mobile robot from clearpath

2024-10-01 15:16 UTC, martinleroux requested changes
Also move the entire ClearPath inside another directory so that the path becomes

ros2_kortex/3rdParty/Mobile_platform_integration

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +6. Modify the `gz_sim.launch.py` using the following command:
Explain why this needs to be done.

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +6. Modify the `gz_sim.launch.py` using the following command:
Also explain what modification is performed.

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +7. Modify the simulation world using the following command:
Explain why this needs to be done and the modification that is done.

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +8. Modify the simulation configuration using the following command:
Explain

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +9. Run the following command in **NEW** terminal window:
Explain what this does

2024-10-01 15:16 UTC, martinleroux commented on clearpath/README.md
> +2. If you are using Python >=3.10 (it will probably be the case), replace `import collections` by `import collections.abc as collections` in the following files: `~/.local/lib/python3.10/site-package
Alternatively, install protobuf v3.20 and install kortex_api with the --no-deps argument.

2024-10-01 15:17 UTC, martinleroux commented on clearpath/README.md
> +# Gen3 + Husky Integration
Begin file by explaining what this content does before jumping into installation instructions.

2024-10-09 23:18 UTC, aalmrad commented on clearpath/README.md
> +# Gen3 + Husky Integration
done

2024-10-09 23:21 UTC, aalmrad commented on clearpath/README.md
> +9. Run the following command in **NEW** terminal window:
done

2024-10-09 23:37 UTC, aalmrad commented on clearpath/README.md
> +8. Modify the simulation configuration using the following command:
done

2024-10-09 23:38 UTC, aalmrad commented on clearpath/README.md
> +7. Modify the simulation world using the following command:
done

2024-10-10 20:51 UTC, aalmrad commented on clearpath/README.md
> +2. If you are using Python >=3.10 (it will probably be the case), replace `import collections` by `import collections.abc as collections` in the following files: `~/.local/lib/python3.10/site-package
done

2024-10-10 20:52 UTC, aalmrad commented on clearpath/README.md
> +6. Modify the `gz_sim.launch.py` using the following command:
done

2024-10-10 23:17 UTC, pradyum commented
@aalmrad I don't understand why **clearpath robot's package** has to be in **ros2_kortex** repository. Could you tell me why it is required to be in this repo?

2024-10-10 23:41 UTC, aalmrad commented
Hello @pradyum,

The objective is to mount the Gen3 robot form Kinova on a Husky mobile platform from clearpath.

Sincerely,
Abed

2024-10-15 17:35 UTC, martinleroux approved these changes

2024-10-15 17:36 UTC, merged