Introduce fault controller
Kinovarobotics/ros2_kortex pull request #63
Opened 2021-11-29 14:30 UTC by livanov93

2021-11-29 15:37 UTC, destogl requested changes
The most important change would be to use Realtime Publisher in the controller. Other changes are rather cosmetic.

2021-11-29 15:37 UTC, destogl commented on kortex2_bringup/launch/kortex_control.launch.py
> +            description="Robot hand controller to start.",
```suggestion
            description="Name of the 'fault controller'.",
```

2021-11-29 15:37 UTC, destogl commented on kortex2_controllers/CMakeLists.txt
> +find_package(std_srvs REQUIRED)
These packages are deprecated. We should probably use then "example_msgs" package instead.

2021-11-29 15:37 UTC, destogl commented on kortex2_controllers/src/fault_controller.cpp
> +  config.names.emplace_back("reset_fault/in_fault");
"in_fault" is a bit confusing name. Can you make it more descriptive? Does this mean "internal_fault"?

2021-11-29 15:37 UTC, destogl commented on kortex2_controllers/include/kortex2_controllers/fault_controller.hpp
> +  rclcpp::Publisher<FbkType>::SharedPtr fault_pub_;
You should use Realtime publisher. See example in broadcasters.

2021-11-29 15:37 UTC, destogl commented on kortex2_controllers/src/fault_controller.cpp
> +  RCLCPP_INFO(node_->get_logger(), "Trying to reset faults on kinova controller.");
If you find this output useful, then also an output that the fault is resetted could be useful.

2021-12-08 10:56 UTC, livanov93 commented on kortex2_controllers/include/kortex2_controllers/fault_controller.hpp
> +  rclcpp::Publisher<FbkType>::SharedPtr fault_pub_;
3bfe4b5

2021-12-08 10:57 UTC, livanov93 commented on kortex2_controllers/src/fault_controller.cpp
> +  config.names.emplace_back("reset_fault/in_fault");
ab09b14

2021-12-08 10:57 UTC, livanov93 commented on kortex2_controllers/CMakeLists.txt
> +find_package(std_srvs REQUIRED)
ab09b14

2021-12-08 10:57 UTC, livanov93 commented on kortex2_bringup/launch/kortex_control.launch.py
> +            description="Robot hand controller to start.",
ab09b14

2021-12-08 11:01 UTC, livanov93 commented on kortex2_controllers/src/fault_controller.cpp
> +  RCLCPP_INFO(node_->get_logger(), "Trying to reset faults on kinova controller.");
f301d3e

2021-12-08 12:05 UTC, livanov93 commented
@destogl This is ready to be merged, some ROS1 files and kinova API are not formatted well. This is already addressed in PR for removal of ROS1 stuff. Other parts will be fixed in additional PRs.

2021-12-08 17:33 UTC, destogl approved these changes
Looking good! Thanks for addressing my comments!

I would also propose to move fault controller to a separate library, but this is more like nitpick so you can do it here, in the follow-up or sometime in the future.

2021-12-08 17:33 UTC, destogl commented on kortex2_controllers/CMakeLists.txt
> +add_library(${PROJECT_NAME} SHARED src/twist_controller.cpp src/fault_controller.cpp)
I would add fault_controller to a separate library.

2021-12-09 13:20 UTC, merged