Move MoveIt Config specific files out of bringup package
Kinovarobotics/ros2_kortex pull request #91
Opened 2023-04-26 18:14 UTC by abake48

Since the current state of `kortex_moveit.launch.py` is broken, now would be a good time to get the MoveIt config package cleaned up. 

This will clear up [this issue](https://github.com/PickNikRobotics/ros2_kortex/issues/33)
and is part of the work needed to [remove moveit ROS 1 packages](https://github.com/PickNikRobotics/ros2_kortex/issues/31)

2023-05-01 21:59 UTC, moriarty commented on kortex_moveit_config/package.xml
> +  <maintainer email="avannobel@kinova.ca" />
I assume this is the original author of the ROS1 config but we should check what should go here for the ROS 2 version maintainer.

2023-05-02 12:39 UTC, MarqRazz reviewed
Are you planning to run MSA to create the `moveit_config` packages? It uses the `MoveItConfigsBuilder` to give the users an easy way to simulate the hardware.

2023-05-02 12:39 UTC, MarqRazz commented on kortex2_bringup/launch/gen3.launch.py
> +    declared_arguments.append(DeclareLaunchArgument("dof", description="DoF of robot."))
Can you add a default_value here? I think it should load the Gen3 if the user does not specify.

2023-05-02 12:39 UTC, MarqRazz commented on kortex2_bringup/launch/gen3.launch.py
> +            "robot_type": "gen3",
This should be a launch argument.

2023-05-02 12:39 UTC, MarqRazz commented on kortex2_bringup/launch/kortex_control.launch.py
>      )
This controller can not be started while the `JTC` is running. The hardware only allows a single command mode be active.

2023-05-02 12:39 UTC, MarqRazz commented on kortex_moveit_config/config/kortex_servo.yaml
> +use_gazebo: false # Whether the robot is started in a Gazebo simulation environment
I recommend you add some comments to this file that the hardware does not perform well with Servo (we recommend you use the `twist_controller` interface on the robot) and this should only be used for simulation.

2023-05-02 14:51 UTC, abake48 commented on kortex_moveit_config/package.xml
> +  <maintainer email="avannobel@kinova.ca" />
I'll ask about this today in standup. I wasn't sure if I should change them but it makes sense in my mind to

2023-05-02 15:00 UTC, abake48 commented on kortex2_bringup/launch/gen3.launch.py
> +            "robot_type": "gen3",
I made this launch file specifically for launching the gen 3 arm. It was an attempt at mirroring the [UR Bringup package](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/main/ur_bringup/launch). Would you advise against doing so? I wasn't sure if I should create a bringup package for each arm or just have launch files for each.

2023-05-02 15:10 UTC, abake48 commented
> Are you planning to run MSA to create the `moveit_config` packages? It uses the `MoveItConfigsBuilder` to give the users an easy way to simulate the hardware.

I wasn't initially but this would be a good place to actually use MSA and build out/report missing features. I'll give it a shot

2023-05-02 20:12 UTC, MarqRazz commented on kortex2_bringup/launch/gen3.launch.py
> +            "robot_type": "gen3",
Sorry I missed that this was specifically for the Gen3. This is fine, but think the default should also include a working gripper.

2023-05-02 20:15 UTC, MarqRazz commented
> I wasn't initially but this would be a good place to actually use MSA and build out/report missing features. I'll give it a shot

Let me know if you run into any issues. We might want to get the robotiq swapped in before we make the moveit_configs (I will try and get to this tomorrow morning).

2023-05-02 20:54 UTC, abake48 commented
> Let me know if you run into any issues.

Ran into an issue right off the bat: turns out the Gen 3 7dof urdfs were out of date so I made a [PR](https://github.com/PickNikRobotics/ros2_kortex/pull/94) to get those updated and working with MSA

2023-05-04 15:03 UTC, MarqRazz reviewed
Looks like you still have a bunch of old launch files in some of the moveit_configs. What is the goal here? Just to rename the folder `kotrex_move_it_config`?

2023-05-04 15:03 UTC, MarqRazz commented on kortex_moveit_config/CMakeLists.txt
Why did you add this file and then add a COLCON_IGNORE to the folder?

2023-05-04 15:20 UTC, abake48 commented on kortex_moveit_config/CMakeLists.txt
I was working on updating the MoveIt configs in this PR but have decided to make a separate PR for that. I initially tried to have the moveit config as a single package but I now see that that is a bad idea. The CMakeLists.txt file and COLCON_IGNORE are artifacts of that. I'll clean this up now

2023-05-09 14:18 UTC, moriarty requested changes
The only change I would request is the version number because we'll probably want to release 1.0.0 when we actually launch, and just bump all versions at once.

But It's not a strong blocking request and I could be convinced otherwise.

I left a question about the 2018 copywrite on a new file, I assume GitHub just isn't able to track that file is just being moved.

And I would add the comment documenting what the environment variable does with cppcheck

2023-05-09 14:18 UTC, moriarty commented on .pre-commit-config.yaml
> +        entry: env AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=1 ament_cppcheck
```suggestion
        # enable slow version of cpp check: https://github.com/ament/ament_lint/pull/345
        entry: env AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=1 ament_cppcheck
```

2023-05-09 14:18 UTC, moriarty commented on kortex_moveit_config/readme.md
> +* Copyright (c) 2018 Kinova inc. All rights reserved.
GitHub says this is a new file, are you moving it from somewhere?

2023-05-09 14:18 UTC, moriarty commented on kortex2_bringup/package.xml
> +  <version>1.0.0</version>
```suggestion
  <version>0.0.1</version>
```

Are we ready to call this 1.0.0 or should we call it 0.0.1 and then bump it when we actually make the public launch?

2023-05-09 14:57 UTC, abake48 commented on kortex_moveit_config/readme.md
> +* Copyright (c) 2018 Kinova inc. All rights reserved.
I moved it from `kinova_move_it_config`. Unsure why it says it's a new file

2023-05-09 14:57 UTC, abake48 commented on kortex2_bringup/package.xml
> +  <version>1.0.0</version>
I was thinking we should bump it on public release.

2023-05-10 15:24 UTC, moriarty approved these changes

2023-05-10 15:25 UTC, merged