Convert package to use robotiq_description and update xacros
Kinovarobotics/ros2_kortex pull request #95
Opened 2023-05-03 20:52 UTC by MarqRazz

This PR removed the redundant models for the robotiq gripper and uses robotiq_description as a dependency. This setup is also super close to working in Ignition Gazebo.

TODO:
- [x] Update package.xml
- [x] Test with Ignition Gazebo
- [ ] Finish removing Gazebo classic support
- [x] Update Robotiq macro to point to one named the specific model number (@abake48 is working on a PR over there)

2023-05-04 03:11 UTC, MarqRazz commented
Got it converted over to the robotiq_description package and working in Ignition (I will update the launch files in another PR because a working gripper also depends on [this PR](https://github.com/ros-controls/gz_ros2_control/pull/86)).

This depends on [PR#17](https://github.com/PickNikRobotics/ros2_robotiq_gripper/pull/17) in the Robotiq repo to rename the urdf xacro.
![kortex_gripper_ignition](https://user-images.githubusercontent.com/25058794/236104757-e650c657-ea32-406f-a7a2-d74c77dac640.gif)

2023-05-04 14:03 UTC, abake48 requested changes
As part of this PR, can you remove the out of date URDFs in the arms directory so I can close the other PR I have open? 

I was able to use the xacro in MSA without issue so I agree with you that those URDFs can go.

2023-05-04 14:20 UTC, MarqRazz commented
> As part of this PR, can you remove the out of date URDFs in the arms directory so I can close the other PR I have open?
> 
> I was able to use the xacro in MSA without issue so I agree with you that those URDFs can go.

:+1: 

I think I'm going to remove Gazebo classic stuff in a follow up PR. This is getting pretty big.

2023-05-04 15:07 UTC, abake48 commented
Does `kortex_description/package.xml` need to have `robotiq_description` as an `exec_depend`? I'm getting a runtime error when trying to launch the arm from the bringup package.

2023-05-04 15:11 UTC, MarqRazz commented
It does have `robotiq_description` as an `exec_depend`. That package is not released so you need to have it from source to test this. What `.repos` files are we going to maintain? I can update it to include the robotiq.

2023-05-04 16:50 UTC, abake48 commented
> What .repos files are we going to maintain? I can update it to include the robotiq.

The `ros2_kortex.repos` and `ros2_kortex.humble.repos` are the two .repos files we are going to maintain.

2023-05-04 19:30 UTC, abake48 requested changes

2023-05-04 19:30 UTC, abake48 commented on kortex_description/robots/gen3.xacro
> +    <xacro:arg name="sim_ignition" default="false" />
```suggestion
    <xacro:arg name="sim_ignition" default="false" />
    <xacro:arg name="sim_issac" default="false" />
```

2023-05-04 19:30 UTC, abake48 commented on kortex_description/robots/gen3.xacro
> +        sim_ignition="$(arg sim_ignition)" >
```suggestion
        sim_ignition="$(arg sim_ignition)" 
        sim_issac="$(arg sim_isaac)" >
```

2023-05-05 02:25 UTC, moriarty approved these changes
Left a question, but it is none-blocking. approving

2023-05-05 02:25 UTC, moriarty commented on kortex_description/arms/gen3/7dof/urdf/kortex.ros2_control.xacro
> +          <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>
Should this be added as a dependency? or assume if they install the sim package it will come in that way.
Have you been testing on isaac sim?

2023-05-05 15:03 UTC, abake48 approved these changes

2023-05-05 15:07 UTC, MarqRazz commented on kortex_description/arms/gen3/7dof/urdf/kortex.ros2_control.xacro
> +          <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>
I have been testing Isaac and will make future PR's to enable it. Right now that package is not release so it will need to be added to the .repos file.

2023-05-05 15:07 UTC, merged